### ISSUE TITLE
Compile SCSS with Gulp

### ISSUE THREAD

**Issue by leomp12** [ecomclub/storefront-framework#31]
We're having some troubles with serve script on Windows env because of fatal errors fired by `mini-css-extract-plugin`. 

As I don't know why it's happening, the new idea is to solve it replacing `mini-css-extract-plugin` + `sass-loader` by `gulp` + `gulp-sass`, which is also a better solution to compile SCSS (Webpack is better for JS).

### TODO
- [ ] Create a Gulp task to compile SCSS `template/scss/styles.scss` to `output/storefront.css` with source map;
- [ ] Debug SASS errors properly;
- [ ] Watch SCSS source files to re-run gulp task;
- [ ] Start Gulp on `serve` and `build` (require on `bin/bundler` background?);
- [ ] Stop doing this same task on `webpack.config.js`;

**Comment by leomp12** [comment]
It can result in problems with `vue-loader` https://github.com/ecomclub/storefront-framework/issues/29

**Comment by leomp12** [comment]
Bug was not with `mini-css-extract-plugin`
